# Generated by Django 3.2.25 on 2025-09-28 23:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_icon', models.ImageField(blank=True, null=True, upload_to='img/icons/')),
                ('cat_parent_id', models.IntegerField(blank=True, null=True)),
                ('cat_free_flag', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.ImageField(blank=True, null=True, upload_to='stores/images/')),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('status_store', models.CharField(choices=[('branding', '1st Branding'), ('maintenance', 'Maintenance')], default='branding', max_length=20, verbose_name='Estado de la tienda')),
                ('temporada', models.CharField(max_length=255)),
                ('pos_contact', models.CharField(db_column='POS_contact', max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=25, null=True)),
                ('distributor_1', models.CharField(max_length=255)),
                ('distributor_2', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('fax', models.CharField(blank=True, max_length=25, null=True)),
                ('mobile', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('embed_video', models.CharField(blank=True, max_length=255, null=True)),
                ('default_media', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('nombre_tendero', models.CharField(blank=True, max_length=180, null=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopmaps.categories')),
            ],
        ),
        migrations.CreateModel(
            name='StoresImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopmaps.images')),
                ('stores', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopmaps.stores')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmaps.project')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmaps.stores')),
            ],
        ),
    ]
