# Generated by Django 3.2.25 on 2025-09-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmaps', '0002_auto_20250928_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código'),
        ),
    ]
