# Generated by Django 3.2.25 on 2025-09-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmaps', '0003_alter_city_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='image',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=2, verbose_name='Imagenes Posters'),
        ),
        migrations.AddField(
            model_name='stores',
            name='image1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=2, verbose_name='Imagenes 5*5 Sticker'),
        ),
        migrations.AddField(
            model_name='stores',
            name='image2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=2, verbose_name='Imagenes 8*8 Sticker'),
        ),
        migrations.AddField(
            model_name='stores',
            name='image3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=2, verbose_name='Imagenes Flange'),
        ),
        migrations.AddField(
            model_name='stores',
            name='image4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=2, verbose_name='Colgarin'),
        ),
    ]
