# Generated by Django 3.2.25 on 2025-09-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmaps', '0004_auto_20250928_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='distributor_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='distributor_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='pos_contact',
            field=models.CharField(blank=True, db_column='POS_contact', max_length=255, null=True),
        ),
    ]
