# Generated by Django 3.2.25 on 2025-09-30 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmaps', '0005_auto_20250929_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopmaps.stores'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stores',
            name='status_store',
            field=models.CharField(choices=[('1st Branding', '1st Branding'), ('Maintenance', 'Maintenance')], default='branding', max_length=20, verbose_name='Estado de la tienda'),
        ),
        migrations.DeleteModel(
            name='StoresImages',
        ),
    ]
