# Generated by Django 3.2.25 on 2025-10-03 00:36

import apps.shopmaps.models.stores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmaps', '0006_auto_20250929_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=apps.shopmaps.models.stores.store_image_upload_path),
        ),
    ]
