# Generated by Django 3.2.25 on 2025-10-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmaps', '0008_auto_20251002_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='temporada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
