# Generated by Django 3.2.25 on 2025-10-03 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmaps', '0009_alter_stores_temporada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopmaps.stores'),
        ),
    ]
