# Generated by Django 3.2.25 on 2025-10-03 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmaps', '0010_alter_images_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopmaps.stores'),
            preserve_default=False,
        ),
    ]
