# Generated by Django 3.2.25 on 2025-10-03 23:44

import apps.shopmaps.models.stores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmaps', '0011_alter_images_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.shopmaps.models.stores.store_image_upload_path),
        ),
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
