# Generated by Django 3.2.25 on 2025-10-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmaps', '0012_auto_20251003_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopmaps.categories'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopmaps.city', verbose_name='Ciudad'),
        ),
    ]
