# Generated by Django 3.2.25 on 2025-10-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmaps', '0013_auto_20251004_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopmaps.project'),
        ),
    ]
